### ISSUE TITLE
Try to send JSON formatted string as MQTT message doesn't work

### ISSUE THREAD

**Issue by KmanOz** [Suxsem/Mqttduino#4] opened 2015-09-09 14:21 UTC
Hi

First, thank you. This was exactly what I was looking for and so far it's bullet proof. I want to send JSON strings as an mqtt message. i.e "1" for on and "0" for off.

It just does't publish a message at all when I try and send this. This is my code:

mqttPublish(MQTT_TOPIC2"/stat", "\"1\"", 0);

If I remove the quotes and send a plain 1 or 0 I have no issues but of course it isn't JSON compliant.

Any suggestions? Excuse my ignorance if it is something obvious.

Thank You

**Comment by thomasvnl** [comment] 2017-01-19 11:43
@KmanOz Please read the [JSON homepage](http://json.org) about the format first because this is obviously a non-issue caused by bad formatting. @Suxsem should close this issue.

**Closed as completed** 2017-01-19 12:23 UTC

**Comment by KmanOz** [comment] 2018-06-20 13:42
Hi

Have come back to this project again and am still having issues.

In my code:

mqttPublish(DEBUG_TOPIC , "DHT Read Error" , MQTTqos);

works fine yet

mqttPublish(DEBUG_TOPIC , "\"DHT Read Error\"" , MQTTqos);

which would yield "DHT Read Error" as the published message does not work. In fact if I use anything but standard ASCII characters the message does not publish as per my original issue. Do you have any ideas at all?

LOL this is not displaying correctly because of Markdown but I want quotes around my message which is usually Backslash followed by " in the Arduino code.
